<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxmZFYm\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxmZFYm/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerGxmZFYm.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerGxmZFYm\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerGxmZFYm\App_KernelTestDebugContainer([
    'container.build_hash' => 'GxmZFYm',
    'container.build_id' => '5133ef2b',
    'container.build_time' => 1636368146,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxmZFYm');
