<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBkxx1U7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBkxx1U7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBkxx1U7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBkxx1U7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBkxx1U7\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bkxx1U7',
    'container.build_id' => '16e25952',
    'container.build_time' => 1636382764,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBkxx1U7');
