<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWvHN65G\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWvHN65G/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWvHN65G.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWvHN65G\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWvHN65G\App_KernelDevDebugContainer([
    'container.build_hash' => 'WvHN65G',
    'container.build_id' => 'cb16f772',
    'container.build_time' => 1636367347,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWvHN65G');
