<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'character' => [[], ['_controller' => 'App\\Controller\\CharacterController::index'], [], [['text', '/character']], [], []],
    'character_display' => [['identifier'], ['_controller' => 'App\\Controller\\CharacterController::display'], [], [['variable', '/', '[^/]++', 'identifier', true], ['text', '/character/display']], [], []],
    'character_create' => [[], ['_controller' => 'App\\Controller\\CharacterController::create'], [], [['text', '/character/create']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
