<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'character_redirect_index' => [[], ['_controller' => 'App\\Controller\\CharacterController::redirectIndex'], [], [['text', '/character']], [], []],
    'character_index' => [[], ['_controller' => 'App\\Controller\\CharacterController::index'], [], [['text', '/character/index']], [], []],
    'character_display' => [['identifier'], ['_controller' => 'App\\Controller\\CharacterController::display'], ['identifier' => '([a-z0-9]{40})'], [['variable', '/', '(?:[a-z0-9]{40})', 'identifier', true], ['text', '/character/display']], [], []],
    'character_create' => [[], ['_controller' => 'App\\Controller\\CharacterController::create'], [], [['text', '/character/create']], [], []],
    'character_modify' => [['identifier'], ['_controller' => 'App\\Controller\\CharacterController::modify'], ['identifier' => '([a-z0-9]{40})'], [['variable', '/', '(?:[a-z0-9]{40})', 'identifier', true], ['text', '/character/modify']], [], []],
    'character_delete' => [['identifier'], ['_controller' => 'App\\Controller\\CharacterController::delete'], ['identifier' => '([a-z0-9]{40})'], [['variable', '/', '(?:[a-z0-9]{40})', 'identifier', true], ['text', '/character/delete']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
